apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: cg-deployment
spec:
  selector:
    matchLabels:
      app: cg-devops-project
  replicas: 2 # tells deployment to run 2 pods matching the template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: cg-devops-project
    spec:
      containers:
      - name: cg-devops-project
        image: sg75/simple-cg-image:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
