apiVersion: v1
kind: Service
metadata:
  name: cg-service
  labels:
    app: cg-devops-project
spec:
  selector:
    app: cg-devops-project
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000
