---
- name: Create pods using deployment
  hosts: k8s-VM
  become: true
  user: root

  tasks:
  - name: create a deployment
    command: kubectl apply -f cg-deploy.yml

  - name: update deployment with new pods if image updated in docker hub
    command: kubectl rollout restart deployment.v1.apps/cg-deployment


